<footer class="bg-secondary pt-2">
         <div class="container ">
            <div class="row">
               <div class="col-md-4">
                  <h3>КОНТАКТИ</h3>
                  <p><span><i class="fas fa-phone"></i></span> +359889813040</p>
                  <p><span><i class="fas fa-at"></i></span> office@mysmartwatch.bg</p>
                  <p><span><i class="fas fa-map-marker-alt"></i></span> Sofia</p>
               </div>                       n                                                      
               <div class="col-md-4">
                  <h3>КАТЕГОРИИ</h3>
                  <div class="d-inline-block">
                     <div >
                        <a href="products.php"> Смарт часовници</a>
                     </div>
                     <div>
                        <a href="products.php" title="смарт гривни">Смарт гривни</a>
                     </div>
                  </div>
               </div>
               <div class="col-md-4 d-block">
                  <h3>КАРТА НА САЙТА</h3>
                  <div>
                     <a href="index.php" title="начало" >НАЧАЛО</a>
                  </div>
                  <div>
                     <a href="products.php" title="продукти">ПРОДУКТИ</a>
                  </div>
                  <div>
                     <a href="aboutus.php" title="за нас">ЗА НАС</a>
                  </div>
                  <div>
                     <a href="contactus.php" title="контакти">КОНТАКТИ</a>
                  </div>
               </div>
            </div>
         </div>
         
      </footer>