 
      <header>
         <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-10" id="main-nav">
            <div class="container">
               <a href="index.php" class="navbar-brand">
                  <img src="img/logo.png" width="50" height="50" alt="logo">
                  <h3 class="d-inline align-middle">MySmartwatch</h3>
               </a>
               <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
               <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarCollapse">
                  <ul class="navbar-nav ml-auto">
                     <li class="nav-item active">
                        <a href="index.php" class="nav-link"><span><i class="fas fa-house-damage"></i></span> НАЧАЛО</a>
                     </li>
                     <li class="nav-item">
                        <a href="products.php" class="nav-link"><span><i class="fab fa-product-hunt"></i></span> ПРОДУКТИ</a>
                     </li>
                     <li class="nav-item">
                        <a href="aboutus.php" class="nav-link"><span><i class="fas fa-info"></i></span> ЗА НАС</a>
                     </li>
                     <li class="nav-item">
                        <a href="contactus.php" class="nav-link"><span><i class="far fa-id-card"></i></span> КОНТАКТИ</a>
                     </li>
                     <li class="nav-item">
                        <a href="account.php" class="nav-link account"><span><i class="fas fa-user"></i></span> ПРОФИЛ <span><i class="fas fa-caret-down"></i></span></a>
                        <div class="account_menu container-fluid">
                        <div class="enter">
                              <a href="#"><button class="btn btn-block text-left"><span><i class="fas fa-sign-in-alt"></i></span> ВЛЕЗ</button></a>
                        </div>
                        <div class="register"> 
                              <a href="register.php" ><button class="btn btn-block text-left"><span><i class="far fa-share-square"></i></span>НОВ ПРОФИЛ</button></a>
                          
                     </div> 
                       </div>
                     </li>
                  </ul>
                  <form class="form-inline mr-0 my-2 my-lg-0 ">
                     <input class="form-control form-control-sm mr-sm-2 search" type="search" placeholder="Търсене" aria-label="Търсене">
                     <button class="btn btn-sm btn-outline-light my-2 my-sm-0" type="submit">ТЪРСЕНЕ</button>
                  </form>
               </div>
            </div>
         </nav>
      </header>

      